---
# tasks file for webserver
- name: mounting share
  command: sudo mount -t efs -o tls,accesspoint=fsap-07669e906adf5426c fs-08e7c3c24b7496c5c:/ /var/www

- name: install httpd on the webserver
  ansible.builtin.yum:
    enablerepo: "BaseOS,AppStream"
    name: "httpd"
    state: present

- name: ensure httpd is started and enabled
  ansible.builtin.service:
     name: httpd 
     state: started 
     enabled: yes

- name: install PHP
  ansible.builtin.yum:
    name:
      - php 
      - php-mysqlnd
      - php-gd 
      - php-curl
      - php-common
      - php-fpm
      - php-mbstring
      - php-opcache 
      - php-xml
      - php-intl 
      - php-json
    state: present

- name: ensure php-fpm is started and enabled
  ansible.builtin.service:
     name: php-fpm
     state: reloaded
     enabled: yes
  notify: Restart httpd



- import_tasks: setup-site.yml

- import_tasks: setup-db.yml